export const enum ViewMode {
  STARTUP_VALIDATION = "startup-validation",
  INITIAL = "initial",
  DRAWING = "drawing",
  WORKSPACE_SELECTION = "workspace-selection",
  EXPORT_FORM = "export-form",
  EXPORT_OPTIONS = "export-options",
  ORDER_RESULT = "order-result",
}

export const enum DrawingTool {
  POLYGON = "polygon",
  RECTANGLE = "rectangle",
}

export const enum FormFieldType {
  TEXT = "text",
  NUMBER = "number",
  TEXTAREA = "textarea",
  SELECT = "select",
  MULTI_SELECT = "multi-select",
  CHECKBOX = "checkbox",
  PASSWORD = "password",
  FILE = "file",
  DATE_TIME = "date-time",
  URL = "url",
  SWITCH = "switch",
  RADIO = "radio",
  SLIDER = "slider",
  NUMERIC_INPUT = "numeric-input",
  TAG_INPUT = "tag-input",
  COLOR = "color",
  DATE = "date",
  TIME = "time",
  EMAIL = "email",
  PHONE = "phone",
  SEARCH = "search",
  MESSAGE = "message",
  TABLE = "table",
  MONTH = "month",
  WEEK = "week",
  COORDSYS = "coord-sys",
  ATTRIBUTE_NAME = "attribute-name",
  ATTRIBUTE_LIST = "attribute-list",
  DB_CONNECTION = "db-connection",
  WEB_CONNECTION = "web-connection",
  TEXT_OR_FILE = "text-or-file",
  REPROJECTION_FILE = "reprojection-file",
  SCRIPTED = "scripted",
  GEOMETRY = "geometry",
  HIDDEN = "hidden",
}

export const enum ErrorSeverity {
  INFO = "info",
  WARNING = "warning",
  ERROR = "error",
}

export const enum ErrorType {
  VALIDATION = "validation",
  CONFIG = "config",
  NETWORK = "network",
  MODULE = "module",
  GEOMETRY = "geometry",
}

export const enum HttpMethod {
  GET = "GET",
  POST = "POST",
  PUT = "PUT",
  DELETE = "DELETE",
}

export const enum ParameterType {
  TEXT = "TEXT",
  INTEGER = "INTEGER",
  FLOAT = "FLOAT",
  BOOLEAN = "BOOLEAN",
  CHECKBOX = "CHECKBOX",
  CHOICE = "CHOICE",
  LISTBOX = "LISTBOX",
  LOOKUP_LISTBOX = "LOOKUP_LISTBOX",
  LOOKUP_CHOICE = "LOOKUP_CHOICE",
  TEXT_OR_FILE = "TEXT_OR_FILE",
  TEXT_EDIT = "TEXT_EDIT",
  PASSWORD = "PASSWORD",
  FILENAME = "FILENAME",
  FILENAME_MUSTEXIST = "FILENAME_MUSTEXIST",
  DIRNAME = "DIRNAME",
  DIRNAME_MUSTEXIST = "DIRNAME_MUSTEXIST",
  DIRNAME_SRC = "DIRNAME_SRC",
  COORDSYS = "COORDSYS",
  STRING = "STRING",
  URL = "URL",
  LOOKUP_URL = "LOOKUP_URL",
  LOOKUP_FILE = "LOOKUP_FILE",
  DATE_TIME = "DATE_TIME",
  DATETIME = "DATETIME",
  DATE = "DATE",
  TIME = "TIME",
  MONTH = "MONTH",
  WEEK = "WEEK",
  COLOR = "COLOR",
  COLOR_PICK = "COLOR_PICK",
  RANGE_SLIDER = "RANGE_SLIDER",
  GEOMETRY = "GEOMETRY",
  MESSAGE = "MESSAGE",
  ATTRIBUTE_NAME = "ATTRIBUTE_NAME",
  ATTRIBUTE_LIST = "ATTRIBUTE_LIST",
  DB_CONNECTION = "DB_CONNECTION",
  WEB_CONNECTION = "WEB_CONNECTION",
  REPROJECTION_FILE = "REPROJECTION_FILE",
  SCRIPTED = "SCRIPTED",
  NOVALUE = "NOVALUE",
}

export const enum JobStatus {
  QUEUED = "QUEUED",
  PULLED = "PULLED",
  RUNNING = "RUNNING",
  SUCCESS = "SUCCESS",
  FME_FAILURE = "FME_FAILURE",
  JOB_FAILURE = "JOB_FAILURE",
  ABORTED = "ABORTED",
}

export const enum FmeActionType {
  SET_VIEW_MODE = "fme/SET_VIEW_MODE",
  RESET_STATE = "fme/RESET_STATE",
  SET_GEOMETRY = "fme/SET_GEOMETRY",
  SET_DRAWING_TOOL = "fme/SET_DRAWING_TOOL",
  COMPLETE_DRAWING = "fme/COMPLETE_DRAWING",
  SET_ORDER_RESULT = "fme/SET_ORDER_RESULT",
  SET_WORKSPACE_ITEMS = "fme/SET_WORKSPACE_ITEMS",
  SET_WORKSPACE_PARAMETERS = "fme/SET_WORKSPACE_PARAMETERS",
  SET_SELECTED_WORKSPACE = "fme/SET_SELECTED_WORKSPACE",
  SET_WORKSPACE_ITEM = "fme/SET_WORKSPACE_ITEM",
  SET_ERROR = "fme/SET_ERROR",
  SET_ERRORS = "fme/SET_ERRORS",
  CLEAR_WORKSPACE_STATE = "fme/CLEAR_WORKSPACE_STATE",
  CLEAR_ERROR = "fme/CLEAR_ERROR",
  RESET_TO_DRAWING = "fme/RESET_TO_DRAWING",
  COMPLETE_STARTUP = "fme/COMPLETE_STARTUP",
  REMOVE_WIDGET_STATE = "fme/REMOVE_WIDGET_STATE",
  SET_LOADING_FLAG = "fme/SET_LOADING_FLAG",
  APPLY_WORKSPACE_DATA = "fme/APPLY_WORKSPACE_DATA",
}
